---
- hosts: testing
  become: true
  vars:
  - src_path: /var/lib/jenkins/workspace/Addressbook-CICD-Pipeline/target
  - dest_path: /var/lib/tomcat9
  tasks:
  - name: Install Tomcat Server Package
    package:
      name: tomcat9
      state: latest
  
  - name: Start Tomcat Service
    service:
      name: tomcat9
      state: started
      enable: true

  - name: Deploy Addressbook Application in Tomcat Server
    copy: 
      src: {{src_path}}/addressbook.war
      dest: {{dest_path}}/webapps
      notify: restart tomcat

  handlers:
  - name: restart tomcat
    service: 
      name: tomcat9
      state: restarted